<a href="https://colab.research.google.com/github/shallabhkhera/NPTEL-Data-Analytics-with-Python/blob/main/Week9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
from scipy.optimize import minimize
import scipy.stats as stats
from statsmodels.formula.api import ols
import pandas as pd
import matplotlib.pyplot as plt

from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score, confusion_matrix, classification_report


In [8]:
url1 = 'https://github.com/shallabhkhera/NPTEL-Data-Analytics-with-Python/blob/main/Simmons.xls?raw=true'
data = pd.read_excel(url1)
data.describe()

Customer    Spending        Card      Coupon
count  100.000000  100.000000  100.000000  100.000000
mean    50.500000    3.333790    0.500000    0.400000
std     29.011492    1.741298    0.502519    0.492366
min      1.000000    1.058000    0.000000    0.000000
25%     25.750000    2.059000    0.000000    0.000000
50%     50.500000    2.805500    0.500000    0.000000
75%     75.250000    4.468250    1.000000    1.000000
max    100.000000    7.076000    1.000000    1.000000

In [9]:
data['Coupon'].unique()

array([0, 1])

In [10]:
data['Coupon'].value_counts()

0    60
1    40
Name: Coupon, dtype: int64

In [11]:
x = data[['Card', 'Spending']]

In [12]:
y = data['Coupon'].values.reshape(-1,1)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

In [13]:
len(x_train), len(x_test), len(y_train), len(y_test)

(75, 25, 75, 25)

In [16]:
lreg = LogisticRegression(solver='lbfgs')
lreg.fit(x_train, y_train.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [19]:
y_predict = lreg.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0])

In [20]:
y_predict_train = lreg.predict(x_train)
y_predict_train

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0])

In [ ]:
y_prod_train = lreg.predict_proba(x_train)[:,1]